// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MyGame.Proto {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgxNeUdhbWUuUHJvdG8qLwoGUkVTVUxUEhIKDlJFU1VM",
            "VF9TVUNDRVNTEAASEQoNUkVTVUxUX0ZBSUxFRBABKl8KDkNIQVJBQ1RFUl9U",
            "WVBFEhkKFUNIQVJBQ1RFUl9UWVBFX1BMQVlFUhAAEhYKEkNIQVJBQ1RFUl9U",
            "WVBFX05QQxABEhoKFkNIQVJBQ1RFUl9UWVBFX01vbnN0ZXIQAiqAAQoPQ0hB",
            "UkFDVEVSX0NMQVNTEhgKFENIQVJBQ1RFUl9DTEFTU19OT05FEAASGwoXQ0hB",
            "UkFDVEVSX0NMQVNTX1dBUlJJT1IQARIaChZDSEFSQUNURVJfQ0xBU1NfV0la",
            "QVJEEAISGgoWQ0hBUkFDVEVSX0NMQVNTX0FSQ0hFUhADKooBCgxFTlRJVFlf",
            "RVZFTlQSFQoRRU5USVRZX0VWRU5UX05PTkUQABIVChFFTlRJVFlfRVZFTlRf",
            "SURMRRABEhkKFUVOVElUWV9FVkVOVF9NT1ZFX0ZXRBACEhoKFkVOVElUWV9F",
            "VkVOVF9NT1ZFX0JBQ0sQAxIVChFFTlRJVFlfRVZFTlRfSlVNUBAEQhL4AQGq",
            "AgxNeUdhbWUuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MyGame.Proto.RESULT), typeof(global::MyGame.Proto.CHARACTER_TYPE), typeof(global::MyGame.Proto.CHARACTER_CLASS), typeof(global::MyGame.Proto.ENTITY_EVENT), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum RESULT {
    [pbr::OriginalName("RESULT_SUCCESS")] Success = 0,
    [pbr::OriginalName("RESULT_FAILED")] Failed = 1,
  }

  /// <summary>
  ///在生成C#代码时，会忽略掉等同于CHARACTER_TYPE的前缀
  /// </summary>
  public enum CHARACTER_TYPE {
    [pbr::OriginalName("CHARACTER_TYPE_PLAYER")] Player = 0,
    [pbr::OriginalName("CHARACTER_TYPE_NPC")] Npc = 1,
    [pbr::OriginalName("CHARACTER_TYPE_Monster")] Monster = 2,
  }

  public enum CHARACTER_CLASS {
    [pbr::OriginalName("CHARACTER_CLASS_NONE")] None = 0,
    [pbr::OriginalName("CHARACTER_CLASS_WARRIOR")] Warrior = 1,
    [pbr::OriginalName("CHARACTER_CLASS_WIZARD")] Wizard = 2,
    [pbr::OriginalName("CHARACTER_CLASS_ARCHER")] Archer = 3,
  }

  public enum ENTITY_EVENT {
    [pbr::OriginalName("ENTITY_EVENT_NONE")] None = 0,
    [pbr::OriginalName("ENTITY_EVENT_IDLE")] Idle = 1,
    [pbr::OriginalName("ENTITY_EVENT_MOVE_FWD")] MoveFwd = 2,
    [pbr::OriginalName("ENTITY_EVENT_MOVE_BACK")] MoveBack = 3,
    [pbr::OriginalName("ENTITY_EVENT_JUMP")] Jump = 4,
  }

  #endregion

}

#endregion Designer generated code
