// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MyGame.Proto {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgxNeUdhbWUuUHJvdG8qIQoGUmVzdWx0EgsKB1NVQ0NF",
            "U1MQABIKCgZGQUlMRUQQASoxCg1DaGFyYWN0ZXJUeXBlEgoKBlBMQVlFUhAA",
            "EgcKA05QQxABEgsKB01vbnN0ZXIQAio1Cg5DaGFyYWN0ZXJDbGFzcxILCgdX",
            "QVJSSU9SEAASCgoGV0laQVJEEAESCgoGQVJDSEVSEAJCEvgBAaoCDE15R2Ft",
            "ZS5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MyGame.Proto.Result), typeof(global::MyGame.Proto.CharacterType), typeof(global::MyGame.Proto.CharacterClass), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Result {
    [pbr::OriginalName("SUCCESS")] Success = 0,
    [pbr::OriginalName("FAILED")] Failed = 1,
  }

  public enum CharacterType {
    [pbr::OriginalName("PLAYER")] Player = 0,
    [pbr::OriginalName("NPC")] Npc = 1,
    [pbr::OriginalName("Monster")] Monster = 2,
  }

  public enum CharacterClass {
    [pbr::OriginalName("WARRIOR")] Warrior = 0,
    [pbr::OriginalName("WIZARD")] Wizard = 1,
    [pbr::OriginalName("ARCHER")] Archer = 2,
  }

  #endregion

}

#endregion Designer generated code
