// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: packetId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MyGame.Proto {

  /// <summary>Holder for reflection information generated from packetId.proto</summary>
  public static partial class PacketIdReflection {

    #region Descriptor
    /// <summary>File descriptor for packetId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wYWNrZXRJZC5wcm90bxIMTXlHYW1lLlByb3RvKrkCCghQYWNrZXRJZBII",
            "CgROT05FEAASGQoVVVNFUl9SRUdJU1RFUl9SRVFVRVNUEAESGgoWVVNFUl9S",
            "RUdJU1RFUl9SRVNQT05TRRACEhYKElVTRVJfTE9HSU5fUkVRVUVTVBADEhcK",
            "E1VTRVJfTE9HSU5fUkVTUE9OU0UQBBIhCh1VU0VSX0NSRUFURV9DSEFSQUNU",
            "RVJfUkVRVUVTVBAFEiIKHlVTRVJfQ1JFQVRFX0NIQVJBQ1RFUl9SRVNQT05T",
            "RRAGEhsKF1VTRVJfR0FNRV9FTlRFUl9SRVFVRVNUEAcSHAoYVVNFUl9HQU1F",
            "X0VOVEVSX1JFU1BPTlNFEAgSGwoXVVNFUl9HQU1FX0xFQVZFX1JFUVVFU1QQ",
            "CRIcChhVU0VSX0dBTUVfTEVBVkVfUkVTUE9OU0UQCkIS+AEBqgIMTXlHYW1l",
            "LlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MyGame.Proto.PacketId), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum PacketId {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("USER_REGISTER_REQUEST")] UserRegisterRequest = 1,
    [pbr::OriginalName("USER_REGISTER_RESPONSE")] UserRegisterResponse = 2,
    [pbr::OriginalName("USER_LOGIN_REQUEST")] UserLoginRequest = 3,
    [pbr::OriginalName("USER_LOGIN_RESPONSE")] UserLoginResponse = 4,
    [pbr::OriginalName("USER_CREATE_CHARACTER_REQUEST")] UserCreateCharacterRequest = 5,
    [pbr::OriginalName("USER_CREATE_CHARACTER_RESPONSE")] UserCreateCharacterResponse = 6,
    [pbr::OriginalName("USER_GAME_ENTER_REQUEST")] UserGameEnterRequest = 7,
    [pbr::OriginalName("USER_GAME_ENTER_RESPONSE")] UserGameEnterResponse = 8,
    [pbr::OriginalName("USER_GAME_LEAVE_REQUEST")] UserGameLeaveRequest = 9,
    [pbr::OriginalName("USER_GAME_LEAVE_RESPONSE")] UserGameLeaveResponse = 10,
  }

  #endregion

}

#endregion Designer generated code
